/*
The selection of the category will be handled by navigating to a new URL via the Link component provided by the React Router package. When the user clicks a Link, the browser is asked to navigate to a new URL without sending any HTTP requests or reloading the application. The details included in the new URL (i.e. selected category) allow different parts of the application to work together.
 */

import React, { Component } from 'react';
import { Link } from 'react-router-dom';

export class CategoryNavigation extends Component {
    render() {
        return <React.Fragment>
            <Link className='btn btn-secondary btn-block' to={this.props.baseUrl}>All</Link>
            { this.props.categories && this.props.categories.map(cat =>
                <Link className='btn btn-secondary btn-block' key={ cat }
                      to={ `${this.props.baseUrl}/${cat.toLowerCase()}`}>{ cat }
                </Link>
            )}
        </React.Fragment>
    }
}

/*
The CategoryNavigation component receives the array of categories through a prop named categories. The component checks to ensure that the array has been defined and then uses the map function to generate content for each array item. React requires a key prop to be applied to the elements generated by the map method so that changes to the array can be handled efficiently. Link components are styled so they appear as buttons. The URLs that the browser will navigate to are the combination of a prop called baseUrl and the category.
 */


